version: "3.8"

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: account_opening
      POSTGRES_USER: marten_user
      POSTGRES_PASSWORD: marten_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
